### ISSUE TITLE
Redis - Unhandled 'error' event

### ISSUE THREAD

**Issue by kawaiipantsu** [kawaiipantsu/tpotce-fullscreen-attackmap#1]
It seems like i still don't safely handle any error events thrown from the Redis module.

Meaning that when the NodeJS Express web server loses it's connectivity to redis backend it will thrown and error and the application dies. I will have to figure out what i'm doing wrong and catch the error event properly.

We need for the application to continue and not throw an error. So that the "re-connection" part of the Redis module kicks in.

Redis thrown error event:
- SocketClosedUnexpectedly
- Error: Socket closed unexpectedly

```
node:events:490
      throw er; // Unhandled 'error' event
      ^

SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (/opt/tpotce-fullscreen-attackmap/node_modules/@redis/client/dist/lib/client/socket.js:195:118)
    at Object.onceWrapper (node:events:627:26)
    at Socket.emit (node:events:512:28)
    at TCP.<anonymous> (node:net:316:12)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (/opt/tpotce-fullscreen-attackmap/node_modules/@redis/client/dist/lib/client/index.js:395:14)
    at RedisSocket.emit (node:events:512:28)
    at RedisSocket._RedisSocket_onSocketError (/opt/tpotce-fullscreen-attackmap/node_modules/@redis/client/dist/lib/client/socket.js:218:10)
    at Socket.<anonymous> (/opt/tpotce-fullscreen-attackmap/node_modules/@redis/client/dist/lib/client/socket.js:195:107)
    at Object.onceWrapper (node:events:627:26)
    at Socket.emit (node:events:512:28)
    at TCP.<anonymous> (node:net:316:12)

Node.js v19.7.0
```

I am currently trying to figure out a way for me to reproduce this error in a way so that i can generate it constantly while i'm testing my code.

**Comment by kawaiipantsu** [comment]
I have now figured out that this error is indeed thrown when the `map_redis` docker container is either crashed or just simply restarted. So i can now without problems re-generate this error on demand.

**Comment by kawaiipantsu** [comment]
Looks like i finally narrowed it down, i was doing the "error handling" on the wrong connection variable.
As this is Redis subscriber based, we run it async and by duplicating the connection so that we handle subscriber on a thread on it's own. That also means that any error handling should be done on that const and not the main connection as that is never initiated via .connect()

After moving the error checking down into the subscribe section, it worked like i had hoped for ! Now i just need to polish the log output and so on. But works.

```
[28-02-2023 17:48:40] info: Redis connected
[28-02-2023 17:48:40] info: Redis ready!
[28-02-2023 17:48:52] error: Socket closed unexpectedly
[28-02-2023 17:48:52] warn: Redis reconnecting
[28-02-2023 17:48:52] error: connect ECONNREFUSED xxx.xxx.xxx.xxx:64379
[28-02-2023 17:48:52] warn: Redis reconnecting
[28-02-2023 17:48:52] error: connect ECONNREFUSED xxx.xxx.xxx.xxx:64379
[28-02-2023 17:48:52] warn: Redis reconnecting
[28-02-2023 17:48:52] error: connect ECONNREFUSED xxx.xxx.xxx.xxx:64379
[28-02-2023 17:48:52] warn: Redis reconnecting
[28-02-2023 17:48:52] error: connect ECONNREFUSED xxx.xxx.xxx.xxx:64379
[28-02-2023 17:48:52] warn: Redis reconnecting
[28-02-2023 17:48:53] info: Redis connected
[28-02-2023 17:48:53] info: Redis ready!
```
